# ============================================================
# Coder Production Platform Management Script (Windows PowerShell)
# Usage: .\scripts\manage.ps1 <command> [arg] [-Llm]
# ============================================================
#Requires -Version 5.1

param(
    [Parameter(Position=0)]
    [string]$Command = "help",
    [Parameter(Position=1)]
    [string]$Arg1 = "",
    [switch]$Llm
)

$ErrorActionPreference = "Stop"
[Console]::OutputEncoding = [System.Text.Encoding]::UTF8

# ---- Paths ----
$ScriptDir   = Split-Path -Parent $MyInvocation.MyCommand.Path
$ProjectRoot = Split-Path -Parent $ScriptDir
$DockerDir   = Join-Path $ProjectRoot "docker"
$ConfigsDir  = Join-Path $ProjectRoot "configs"
$EnvFile     = Join-Path $DockerDir ".env"
$SetupDone   = Join-Path $DockerDir ".setup-done"

$script:UseLlm = $Llm.IsPresent

# ---- Color output ----
function Write-Info { param($msg) Write-Host "[INFO]  $msg" -ForegroundColor Cyan }
function Write-OK   { param($msg) Write-Host "[ OK ]  $msg" -ForegroundColor Green }
function Write-Warn { param($msg) Write-Host "[WARN]  $msg" -ForegroundColor Yellow }
function Write-Fail { param($msg) Write-Host "[FAIL]  $msg" -ForegroundColor Red }

# ---- Docker check ----
function Assert-Docker {
    if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
        Write-Fail "docker not found. Please install Docker Desktop."
        exit 1
    }
    $eap = $ErrorActionPreference; $ErrorActionPreference = 'Continue'
    docker info 2>&1 | Out-Null
    $e = $LASTEXITCODE
    $ErrorActionPreference = $eap
    if ($e -ne 0) { Write-Fail "Docker daemon is not running. Please start Docker Desktop."; exit 1 }

    $eap = $ErrorActionPreference; $ErrorActionPreference = 'Continue'
    docker compose version 2>&1 | Out-Null
    $e2 = $LASTEXITCODE
    $ErrorActionPreference = $eap
    if ($e2 -ne 0) { Write-Fail "docker compose not available. Please upgrade Docker Desktop."; exit 1 }
}

# ---- Initialize directories ----
function Initialize-Dirs {
    foreach ($d in @(
        (Join-Path $DockerDir ""),
        (Join-Path $ConfigsDir "ssl"),
        (Join-Path $ConfigsDir "terraform-providers"),
        (Join-Path $ConfigsDir "vsix"),
        (Join-Path $ProjectRoot "images"),
        (Join-Path $ProjectRoot "logs\nginx")
    )) {
        New-Item -ItemType Directory -Path $d -Force | Out-Null
    }
}

# ---- Read .env file into hashtable ----
function Read-EnvFile {
    $h = @{}
    if (-not (Test-Path $EnvFile)) { return $h }
    Get-Content $EnvFile | ForEach-Object {
        $line = $_.Trim()
        if ($line -and -not $line.StartsWith('#') -and $line -match '^([^=]+)=(.*)$') {
            $h[$matches[1].Trim()] = $matches[2].Trim()
        }
    }
    return $h
}

# ---- Generate random hex string ----
function New-RandomHex {
    param([int]$Bytes = 16)
    $arr = [byte[]]::new($Bytes)
    [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($arr)
    return ($arr | ForEach-Object { '{0:x2}' -f $_ }) -join ''
}

# ============================================================
# init: Create docker/.env config file
# ============================================================
function Invoke-Init {
    Write-Info "Initializing Coder platform configuration..."
    if (Test-Path $EnvFile) {
        $ans = Read-Host "docker\.env already exists. Overwrite? (y/N)"
        if ($ans -notmatch '^[Yy]$') { Write-OK "Keeping existing config."; return }
    }

    $pgPassword = New-RandomHex -Bytes 16

    $serverHost = Read-Host "Server IP or hostname [localhost]"
    if (-not $serverHost) { $serverHost = "localhost" }

    $gatewayPort = Read-Host "Gateway port [8443]"
    if (-not $gatewayPort) { $gatewayPort = "8443" }

    $adminEmail = Read-Host "Coder admin email [admin@company.local]"
    if (-not $adminEmail) { $adminEmail = "admin@company.local" }

    $adminUsername = Read-Host "Coder admin username [admin]"
    if (-not $adminUsername) { $adminUsername = "admin" }

    $adminPasswordSec = Read-Host "Coder admin password (min 8 chars)" -AsSecureString
    $adminPasswordPlain = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto(
        [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($adminPasswordSec))
    if ($adminPasswordPlain.Length -lt 8) {
        $adminPasswordPlain = "Coder@$(Get-Date -Format 'yyyy')"
        Write-Warn "Password too short. Auto-generated: $adminPasswordPlain"
    }

    $anthropicKey = Read-Host "Anthropic API Key (leave blank to skip)"
    $anthropicUrl = Read-Host "Anthropic Base URL for internal proxy (leave blank to skip)"

    $lines = @(
        "# ============================================================",
        "# Coder Production Platform Configuration",
        "# Generated by manage.ps1 init",
        "# ============================================================",
        "",
        "# ---- Network ----",
        "SERVER_HOST=$serverHost",
        "GATEWAY_PORT=$gatewayPort",
        "",
        "# ---- Coder image versions ----",
        "CODER_IMAGE=ghcr.io/coder/coder",
        "CODER_VERSION=latest",
        "WORKSPACE_IMAGE=workspace-embedded",
        "WORKSPACE_IMAGE_TAG=latest",
        "",
        "# ---- Database (auto-generated password) ----",
        "POSTGRES_PASSWORD=$pgPassword",
        "",
        "# ---- Coder admin account (created on first start) ----",
        "CODER_ADMIN_EMAIL=$adminEmail",
        "CODER_ADMIN_USERNAME=$adminUsername",
        "CODER_ADMIN_PASSWORD=$adminPasswordPlain",
        "",
        "# ---- Claude Code API ----",
        "# Option A: Official API  -> set ANTHROPIC_API_KEY, leave ANTHROPIC_BASE_URL blank",
        "# Option B: Internal proxy-> set both (proxy must implement Anthropic /v1/messages)",
        "# Option C: LiteLLM      -> .\manage.ps1 up -Llm, ANTHROPIC_BASE_URL=https://<IP>:8443/llm",
        "# Option D: Manual login -> leave blank, run 'claude' inside workspace",
        "ANTHROPIC_API_KEY=$anthropicKey",
        "ANTHROPIC_BASE_URL=$anthropicUrl",
        "",
        "# ---- LiteLLM AI gateway (optional, enabled with -Llm flag) ----",
        "LITELLM_MASTER_KEY=sk-devenv",
        "INTERNAL_API_BASE=http://10.0.0.1:8000",
        "INTERNAL_API_KEY=your-internal-api-key",
        "",
        "# ---- Internal ports ----",
        "CODER_INTERNAL_PORT=7080"
    )

    $content = $lines -join "`r`n"
    [System.IO.File]::WriteAllText($EnvFile, $content, [System.Text.Encoding]::UTF8)
    Write-OK "Config file created: $EnvFile"
    Write-Warn "Please review and modify $EnvFile as needed."

    $ans2 = Read-Host "Also create LiteLLM config? (y/N)"
    if ($ans2 -match '^[Yy]$') {
        $llmExample = Join-Path $ConfigsDir "litellm_config.yaml.example"
        $llmConfig  = Join-Path $ConfigsDir "litellm_config.yaml"
        if ((Test-Path $llmExample) -and (-not (Test-Path $llmConfig))) {
            Copy-Item $llmExample $llmConfig
            Write-OK "LiteLLM config created: $llmConfig"
            Write-Warn "Edit this file to fill in your internal API address and model name."
        } elseif (Test-Path $llmConfig) {
            Write-Warn "LiteLLM config already exists: $llmConfig"
        }
    }
}

# ============================================================
# ssl: Generate self-signed SSL certificate
# ============================================================
function Invoke-GenSSL {
    param([string]$ServerHost = "")
    Write-Info "Generating self-signed SSL certificate (with SAN)..."
    $sslDir = Join-Path $ConfigsDir "ssl"
    New-Item -ItemType Directory -Path $sslDir -Force | Out-Null

    $altNames = "DNS.1 = localhost`nDNS.2 = coder.local`nDNS.3 = host.docker.internal`nIP.1  = 127.0.0.1`n"
    $cnName   = "localhost"
    if ($ServerHost) {
        $cnName = $ServerHost
        if ($ServerHost -match '^\d+\.\d+\.\d+\.\d+$') {
            $altNames += "IP.2  = $ServerHost`n"
        } else {
            $altNames += "DNS.4 = $ServerHost`n"
        }
        Write-Info "  SAN includes server address: $ServerHost"
    }

    # Find openssl (bundled with Git for Windows)
    $opensslCmd = $null
    foreach ($candidate in @(
        "openssl",
        "C:\Program Files\Git\usr\bin\openssl.exe",
        "C:\Program Files (x86)\Git\usr\bin\openssl.exe"
    )) {
        if (Get-Command $candidate -ErrorAction SilentlyContinue) {
            $opensslCmd = $candidate; break
        }
    }

    if ($opensslCmd) {
        $confLines = @(
            "[req]",
            "default_bits       = 2048",
            "prompt             = no",
            "default_md         = sha256",
            "distinguished_name = dn",
            "x509_extensions    = v3_req",
            "",
            "[dn]",
            "C  = CN",
            "ST = Beijing",
            "L  = Beijing",
            "O  = Coder Platform",
            "CN = $cnName",
            "",
            "[v3_req]",
            "subjectAltName      = @alt_names",
            "keyUsage            = critical, digitalSignature, keyEncipherment",
            "extendedKeyUsage    = serverAuth",
            "basicConstraints    = CA:FALSE",
            "",
            "[alt_names]",
            $altNames
        )
        $opensslConf = $confLines -join "`n"

        $confPath = Join-Path $sslDir "openssl.cnf"
        [System.IO.File]::WriteAllText($confPath, $opensslConf, [System.Text.Encoding]::ASCII)

        $eap = $ErrorActionPreference; $ErrorActionPreference = 'Continue'
        & $opensslCmd req -x509 -newkey rsa:2048 -sha256 -days 825 -nodes `
            -keyout "$sslDir\server.key" `
            -out    "$sslDir\server.crt" `
            -config $confPath 2>&1 | Out-Null
        $exitCode = $LASTEXITCODE
        $ErrorActionPreference = $eap
        Remove-Item $confPath -ErrorAction SilentlyContinue

        if ($exitCode -ne 0) {
            # Retry with output visible for debugging
            Write-Warn "Retrying openssl with output..."
            & $opensslCmd req -x509 -newkey rsa:2048 -sha256 -days 825 -nodes `
                -keyout "$sslDir\server.key" `
                -out    "$sslDir\server.crt" `
                -config (Join-Path $sslDir "openssl.cnf")
            [System.IO.File]::WriteAllText((Join-Path $sslDir "openssl.cnf"), $opensslConf, [System.Text.Encoding]::ASCII)
            & $opensslCmd req -x509 -newkey rsa:2048 -sha256 -days 825 -nodes `
                -keyout "$sslDir\server.key" `
                -out    "$sslDir\server.crt" `
                -config (Join-Path $sslDir "openssl.cnf")
            $exitCode = $LASTEXITCODE
            Remove-Item (Join-Path $sslDir "openssl.cnf") -ErrorAction SilentlyContinue
            if ($exitCode -ne 0) { Write-Fail "openssl certificate generation failed (exit $exitCode)"; exit 1 }
        }
        Write-OK "SSL certificate generated: $sslDir\"
        Write-Warn "Run 'build' to bake this cert into the workspace image."

        # Import to Windows Trusted Root store
        Write-Info "Importing certificate to Windows Trusted Root store (requires admin)..."
        try {
            $certObj = New-Object System.Security.Cryptography.X509Certificates.X509Certificate2(
                (Resolve-Path "$sslDir\server.crt").Path
            )
            $store = New-Object System.Security.Cryptography.X509Certificates.X509Store(
                [System.Security.Cryptography.X509Certificates.StoreName]::Root,
                [System.Security.Cryptography.X509Certificates.StoreLocation]::LocalMachine
            )
            $store.Open([System.Security.Cryptography.X509Certificates.OpenFlags]::ReadWrite)
            $store.Add($certObj)
            $store.Close()
            Write-OK "Certificate imported to Trusted Root -- browser will not show warnings."
        } catch {
            Write-Warn "Failed to import to Trusted Root: $($_.Exception.Message)"
            Write-Warn "Run as Administrator or manually import $sslDir\server.crt"
            Write-Warn "  -> Certificate Manager -> Trusted Root Certification Authorities -> Certificates"
        }
    } else {
        Write-Warn "openssl not found (install Git for Windows to get openssl)."
        Write-Warn "Falling back to PowerShell New-SelfSignedCertificate..."
        $dnsNames = @("localhost", "coder.local", "host.docker.internal")
        if ($ServerHost -and ($ServerHost -notmatch '^\d')) { $dnsNames += $ServerHost }
        $cert = New-SelfSignedCertificate `
            -DnsName $dnsNames `
            -CertStoreLocation "Cert:\LocalMachine\My" `
            -NotAfter (Get-Date).AddYears(1) `
            -KeyAlgorithm RSA -KeyLength 2048 -HashAlgorithm SHA256 `
            -KeyUsage DigitalSignature, KeyEncipherment `
            -TextExtension @("2.5.29.37={text}1.3.6.1.5.5.7.3.1")
        $pfxPath = Join-Path $sslDir "server.pfx"
        $pfxPwd  = ConvertTo-SecureString "coder" -AsPlainText -Force
        Export-PfxCertificate -Cert $cert -FilePath $pfxPath -Password $pfxPwd | Out-Null
        Write-Warn "Generated PFX: $pfxPath"
        Write-Warn "Install Git for Windows then re-run 'ssl' to get PEM format (required by Docker/nginx)."
    }
}

# ============================================================
# pull: Pull platform base images (requires internet)
# ============================================================
function Invoke-Pull {
    Assert-Docker
    $env      = Read-EnvFile
    $coderImg = if ($env["CODER_IMAGE"])       { $env["CODER_IMAGE"] }       else { "ghcr.io/coder/coder" }
    $coderVer = if ($env["CODER_VERSION"])     { $env["CODER_VERSION"] }     else { "latest" }
    $pgVer    = if ($env["POSTGRES_VERSION"]) { $env["POSTGRES_VERSION"] } else { "16" }

    Write-Info "Pulling platform base images..."
    foreach ($img in @("${coderImg}:${coderVer}", "postgres:${pgVer}-alpine", "nginx:alpine")) {
        Write-Info "  Pulling $img"
        docker pull $img
        if ($LASTEXITCODE -ne 0) { Write-Fail "Failed to pull: $img"; exit 1 }
    }
    if ($script:UseLlm) {
        Write-Info "  Pulling ghcr.io/berriai/litellm:main-latest"
        docker pull ghcr.io/berriai/litellm:main-latest
    }
    Write-OK "Base images pulled."
    Write-Warn "Workspace image must be built separately: .\manage.ps1 build"
}

# ============================================================
# build: Build workspace Docker image
# ============================================================
function Invoke-Build {
    Assert-Docker
    $env     = Read-EnvFile
    $imgName = if ($env["WORKSPACE_IMAGE"])     { $env["WORKSPACE_IMAGE"] }     else { "workspace-embedded" }
    $imgTag  = if ($env["WORKSPACE_IMAGE_TAG"]) { $env["WORKSPACE_IMAGE_TAG"] } else { "latest" }

    $sslCrt = Join-Path $ConfigsDir "ssl\server.crt"
    if (-not (Test-Path $sslCrt)) {
        Write-Warn "SSL cert not found. Auto-generating for localhost..."
        Invoke-GenSSL
        Write-Warn "For production: run '.\manage.ps1 ssl <SERVER_IP>' before 'build'."
    }

    Write-Info "Building workspace image: ${imgName}:${imgTag}"
    Write-Info "Note: Full embedded toolchain build may take 20-40 minutes..."
    docker build `
        -f "$DockerDir\Dockerfile.workspace" `
        -t "${imgName}:${imgTag}" `
        $ProjectRoot
    if ($LASTEXITCODE -ne 0) { Write-Fail "Workspace image build failed."; exit 1 }
    Write-OK "Workspace image built: ${imgName}:${imgTag}"
}

# ============================================================
# save: Export images to images\ directory
# ============================================================
function Invoke-Save {
    Assert-Docker
    $env    = Read-EnvFile
    $imgDir = Join-Path $ProjectRoot "images"
    New-Item -ItemType Directory -Path $imgDir -Force | Out-Null

    $coderImg = if ($env["CODER_IMAGE"])         { $env["CODER_IMAGE"] }         else { "ghcr.io/coder/coder" }
    $coderVer = if ($env["CODER_VERSION"])        { $env["CODER_VERSION"] }        else { "latest" }
    $pgVer    = if ($env["POSTGRES_VERSION"])     { $env["POSTGRES_VERSION"] }     else { "16" }
    $wsImg    = if ($env["WORKSPACE_IMAGE"])      { $env["WORKSPACE_IMAGE"] }      else { "workspace-embedded" }
    $wsTag    = if ($env["WORKSPACE_IMAGE_TAG"]) { $env["WORKSPACE_IMAGE_TAG"] } else { "latest" }

    $images = [System.Collections.Generic.List[string]]@(
        "${coderImg}:${coderVer}",
        "postgres:${pgVer}-alpine",
        "nginx:alpine",
        "${wsImg}:${wsTag}"
    )
    if ($script:UseLlm) { $images.Add("ghcr.io/berriai/litellm:main-latest") }

    foreach ($img in $images) {
        $fname = ($img -replace "[:/]", "_") + ".tar"
        $fpath = Join-Path $imgDir $fname
        Write-Info "  Saving $img -> $fname (no progress bar, please wait)..."
        docker save $img -o $fpath
        if ($LASTEXITCODE -ne 0) { Write-Fail "Failed to save: $img"; exit 1 }
        $sizeMB = [math]::Round((Get-Item $fpath).Length / 1MB)
        Write-OK "  Saved ${sizeMB} MB"
    }
    Write-OK "All images saved to images\"
}

# ============================================================
# load: Load images from images\ directory
# ============================================================
function Invoke-Load {
    Assert-Docker
    $imgDir = Join-Path $ProjectRoot "images"
    if (-not (Test-Path $imgDir)) { Write-Fail "images\ directory not found."; exit 1 }
    $tarFiles = Get-ChildItem "$imgDir\*.tar" -ErrorAction SilentlyContinue
    if ($tarFiles.Count -eq 0) {
        Write-Fail "No .tar files in images\. Run 'save' or 'prepare-offline' first."
        exit 1
    }
    foreach ($f in $tarFiles) {
        $sizeMB = [math]::Round($f.Length / 1MB)
        Write-Info "  Loading $($f.Name) (${sizeMB} MB)..."
        docker load -i $f.FullName
        if ($LASTEXITCODE -ne 0) { Write-Fail "Failed to load: $($f.Name)"; exit 1 }
    }
    Write-OK "Images loaded."
}

# ============================================================
# up: Start the platform
# ============================================================
function Invoke-Up {
    Assert-Docker
    Initialize-Dirs

    if (-not (Test-Path $EnvFile)) {
        Write-Fail "docker\.env not found. Run: .\manage.ps1 init"
        exit 1
    }
    $env = Read-EnvFile

    # Auto-generate SSL cert if missing
    $sslCrt = Join-Path $ConfigsDir "ssl\server.crt"
    if (-not (Test-Path $sslCrt)) {
        Write-Warn "SSL cert not found. Auto-generating..."
        $sh = if ($env["SERVER_HOST"]) { $env["SERVER_HOST"] } else { "localhost" }
        Invoke-GenSSL -ServerHost $sh
    }

    # Check workspace image
    $wsImg = if ($env["WORKSPACE_IMAGE"])     { $env["WORKSPACE_IMAGE"] }     else { "workspace-embedded" }
    $wsTag = if ($env["WORKSPACE_IMAGE_TAG"]) { $env["WORKSPACE_IMAGE_TAG"] } else { "latest" }
    $eap = $ErrorActionPreference; $ErrorActionPreference = 'Continue'
    docker image inspect "${wsImg}:${wsTag}" 2>&1 | Out-Null
    $imgExists = $LASTEXITCODE
    $ErrorActionPreference = $eap
    if ($imgExists -ne 0) {
        Write-Warn "Workspace image not found. Auto-building..."
        Invoke-Build
    }

    # Warn if Terraform providers are missing
    $tfProviders = Join-Path $ConfigsDir "terraform-providers\registry.terraform.io"
    if (-not (Test-Path $tfProviders)) {
        Write-Warn "Terraform provider cache not found (configs\terraform-providers\)."
        Write-Warn "Run prepare-offline.ps1 on an internet-connected machine, or ensure Coder can reach registry.terraform.io."
    }

    $logsDir = Join-Path $ProjectRoot "logs\nginx"
    New-Item -ItemType Directory -Path $logsDir -Force | Out-Null

    $composeArgs = if ($script:UseLlm) { @("--profile", "llm", "up", "-d") } else { @("up", "-d") }
    Push-Location $DockerDir
    docker compose @composeArgs
    if ($LASTEXITCODE -ne 0) { Pop-Location; Write-Fail "docker compose up failed."; exit 1 }
    Pop-Location
    Write-OK "Platform started."

    if (-not (Test-Path $SetupDone)) {
        Write-Host ""
        Write-Warn "First-time startup detected. Initializing Coder (30-60 seconds)..."
        Start-Sleep -Seconds 8
        Invoke-SetupCoder
    } else {
        Write-Host ""
        Show-AccessInfo
    }
}

# ============================================================
# down: Stop the platform
# ============================================================
function Invoke-Down {
    Assert-Docker
    $composeArgs = if ($script:UseLlm) { @("--profile", "llm", "down") } else { @("down") }
    Push-Location $DockerDir
    docker compose @composeArgs
    Pop-Location
    Write-OK "Platform stopped."
}

# ============================================================
# status: Show service status
# ============================================================
function Invoke-Status {
    Assert-Docker
    Push-Location $DockerDir
    docker compose ps
    Pop-Location
}

# ============================================================
# logs: Show logs
# ============================================================
function Invoke-Logs {
    Assert-Docker
    Push-Location $DockerDir
    if ($Arg1) {
        docker compose logs -f --tail=100 $Arg1
    } else {
        docker compose logs -f --tail=100
    }
    Pop-Location
}

# ============================================================
# shell: Enter container shell
# ============================================================
function Invoke-Shell {
    Assert-Docker
    if (-not $Arg1) {
        Write-Fail "Specify a service name. Example: .\manage.ps1 shell coder"
        Write-Host "Available services: gateway, coder, postgres, llm-gateway"
        exit 1
    }
    Push-Location $DockerDir
    docker compose exec $Arg1 /bin/bash
    Pop-Location
}

# ============================================================
# setup-coder: First-time init (create admin + push template)
# ============================================================
function Invoke-SetupCoder {
    if (-not (Test-Path $EnvFile)) { Write-Fail "Run 'init' first."; exit 1 }
    $env = Read-EnvFile

    $internalPort = if ($env["CODER_INTERNAL_PORT"]) { $env["CODER_INTERNAL_PORT"] } else { "7080" }
    $baseUrl      = "http://localhost:$internalPort"
    $adminEmail   = if ($env["CODER_ADMIN_EMAIL"])    { $env["CODER_ADMIN_EMAIL"] }    else { "admin@company.local" }
    $adminUser    = if ($env["CODER_ADMIN_USERNAME"]) { $env["CODER_ADMIN_USERNAME"] } else { "admin" }
    $adminPwd     = if ($env["CODER_ADMIN_PASSWORD"]) { $env["CODER_ADMIN_PASSWORD"] } else { "" }
    $serverHost   = if ($env["SERVER_HOST"])          { $env["SERVER_HOST"] }          else { "localhost" }
    $gwPort       = if ($env["GATEWAY_PORT"])         { $env["GATEWAY_PORT"] }         else { "8443" }
    $wsImg        = if ($env["WORKSPACE_IMAGE"])      { $env["WORKSPACE_IMAGE"] }      else { "workspace-embedded" }
    $wsTag        = if ($env["WORKSPACE_IMAGE_TAG"]) { $env["WORKSPACE_IMAGE_TAG"] } else { "latest" }
    $anthropicKey = if ($env["ANTHROPIC_API_KEY"])    { $env["ANTHROPIC_API_KEY"] }    else { "" }
    $anthropicUrl = if ($env["ANTHROPIC_BASE_URL"])   { $env["ANTHROPIC_BASE_URL"] }   else { "" }

    # 1. Wait for Coder to be ready
    Write-Info "Waiting for Coder service to be ready..."
    $ready = $false
    for ($i = 1; $i -le 60; $i++) {
        $eap = $ErrorActionPreference; $ErrorActionPreference = 'Continue'
        try {
            $r = Invoke-WebRequest -Uri "$baseUrl/healthz" -UseBasicParsing -TimeoutSec 3 -ErrorAction Stop
            if ($r.StatusCode -eq 200) { $ready = $true; break }
        } catch { }
        $ErrorActionPreference = $eap
        Write-Host "." -NoNewline
        Start-Sleep -Seconds 3
    }
    Write-Host ""
    if (-not $ready) { Write-Fail "Coder did not become ready within 180 seconds."; exit 1 }
    Write-OK "Coder is ready."

    # 2. Create first admin if not yet created
    $eap = $ErrorActionPreference; $ErrorActionPreference = 'Continue'
    try {
        $chk = Invoke-WebRequest -Uri "$baseUrl/api/v2/users/first" -UseBasicParsing -TimeoutSec 5 -ErrorAction Stop
        $firstUserStatus = $chk.StatusCode
    } catch {
        $firstUserStatus = $_.Exception.Response.StatusCode.Value__
    }
    $ErrorActionPreference = $eap

    if ($firstUserStatus -eq 404) {
        Write-Info "Creating admin account: $adminEmail"
        $body = '{"email":"' + $adminEmail + '","username":"' + $adminUser + '","password":"' + $adminPwd + '","trial":false}'
        $eap = $ErrorActionPreference; $ErrorActionPreference = 'Continue'
        try {
            Invoke-RestMethod -Uri "$baseUrl/api/v2/users/first" -Method POST `
                -ContentType "application/json" -Body $body -ErrorAction Stop | Out-Null
            Write-OK "Admin account created."
        } catch {
            Write-Fail "Failed to create admin account: $_"; exit 1
        }
        $ErrorActionPreference = $eap
    } else {
        Write-Info "Admin account already exists. Skipping creation."
    }

    # 3. Login to get session token
    $loginBody = '{"email":"' + $adminEmail + '","password":"' + $adminPwd + '"}'
    $eap = $ErrorActionPreference; $ErrorActionPreference = 'Continue'
    try {
        $loginResp = Invoke-RestMethod -Uri "$baseUrl/api/v2/users/login" -Method POST `
            -ContentType "application/json" -Body $loginBody -ErrorAction Stop
        $sessionToken = $loginResp.session_token
    } catch {
        Write-Fail "Login failed: $_"; exit 1
    }
    $ErrorActionPreference = $eap

    if (-not $sessionToken) { Write-Fail "Failed to get session token."; exit 1 }
    Write-OK "Logged in. Session token obtained."

    # 4. Check if template already exists
    $eap = $ErrorActionPreference; $ErrorActionPreference = 'Continue'
    try {
        $tmplChk = Invoke-WebRequest -Uri "$baseUrl/api/v2/organizations/default/templates/embedded-dev" `
            -Headers @{ "Coder-Session-Token" = $sessionToken } -UseBasicParsing -TimeoutSec 5 -ErrorAction Stop
        $templateExists = ($tmplChk.StatusCode -eq 200)
    } catch {
        $templateExists = $false
    }
    $ErrorActionPreference = $eap

    if ($templateExists) {
        Write-Warn "Template 'embedded-dev' already exists. Skipping push."
        Write-Warn "To update: .\manage.ps1 setup-coder  (after deleting docker\.setup-done)"
    } else {
        # 5. Copy template directory into container via docker cp, then push with coder CLI
        Write-Info "Pushing workspace template..."
        $tmplDir = Join-Path $ProjectRoot "workspace-template"

        # Ensure clean destination
        $eap = $ErrorActionPreference; $ErrorActionPreference = 'Continue'
        docker exec coder-server sh -c "rm -rf /tmp/template-push && mkdir -p /tmp/template-push" | Out-Null
        $ErrorActionPreference = $eap

        # docker cp handles Windows paths natively (no tar needed)
        docker cp "$tmplDir/." "coder-server:/tmp/template-push/"
        if ($LASTEXITCODE -ne 0) { Write-Fail "Failed to copy template to container."; exit 1 }

        $pushCmd = "CODER_URL=http://localhost:7080 CODER_SESSION_TOKEN=$sessionToken /opt/coder templates push embedded-dev --directory /tmp/template-push --yes --activate --var workspace_image=$wsImg --var workspace_image_tag=$wsTag --var anthropic_api_key=$anthropicKey --var anthropic_base_url=$anthropicUrl ; rm -rf /tmp/template-push"

        $eap = $ErrorActionPreference; $ErrorActionPreference = 'Continue'
        docker exec coder-server sh -c $pushCmd
        $pushExit = $LASTEXITCODE
        $ErrorActionPreference = $eap

        if ($pushExit -eq 0) {
            Write-OK "Workspace template pushed successfully."
        } else {
            Write-Fail "Template push failed (exit $pushExit)."
            Write-Warn "Manual fix: docker exec -it coder-server /bin/sh"
            exit 1
        }
    }

    # Write completion marker
    Get-Date | Set-Content $SetupDone

    Write-Host ""
    Write-Host "========================================" -ForegroundColor Green
    Write-Host " Coder initialization complete!" -ForegroundColor Green
    Write-Host "========================================" -ForegroundColor Green
    Write-Host ""
    Show-AccessInfo
    Write-Host "Admin account: $adminEmail" -ForegroundColor Yellow
}

# ---- Show access info ----
function Show-AccessInfo {
    $env    = Read-EnvFile
    $sh     = if ($env["SERVER_HOST"])  { $env["SERVER_HOST"] }  else { "localhost" }
    $port   = if ($env["GATEWAY_PORT"]) { $env["GATEWAY_PORT"] } else { "8443" }
    Write-Host "Access URLs:" -ForegroundColor Cyan
    Write-Host "  Admin Dashboard: https://${sh}:${port}/" -ForegroundColor White
    Write-Host "  User IDE:        https://${sh}:${port}/@<username>/<workspace>.main/apps/code-server" -ForegroundColor White
    if ($script:UseLlm) {
        Write-Host "  LiteLLM:         https://${sh}:${port}/llm/" -ForegroundColor White
    }
    Write-Host ""
}

# ============================================================
# test-api: Test LLM API connectivity
# ============================================================
function Invoke-TestApi {
    if (-not (Test-Path $EnvFile)) { Write-Fail "Run 'init' first."; exit 1 }
    $env        = Read-EnvFile
    $apiKey     = if ($env["ANTHROPIC_API_KEY"])  { $env["ANTHROPIC_API_KEY"] }  else { "" }
    $apiBaseUrl = if ($env["ANTHROPIC_BASE_URL"]) { $env["ANTHROPIC_BASE_URL"] } else { "" }
    if (-not $apiBaseUrl) { $apiBaseUrl = "https://api.anthropic.com" }

    if (-not $apiKey) { Write-Fail "ANTHROPIC_API_KEY not configured."; exit 1 }
    Write-Info "Testing API connection: $apiBaseUrl"

    $body = '{"model":"claude-haiku-4-5-20251001","max_tokens":16,"messages":[{"role":"user","content":"hi"}]}'

    $eap = $ErrorActionPreference; $ErrorActionPreference = 'Continue'
    try {
        Invoke-RestMethod -Uri "$apiBaseUrl/v1/messages" -Method POST `
            -Headers @{ "x-api-key" = $apiKey; "anthropic-version" = "2023-06-01" } `
            -ContentType "application/json" -Body $body -TimeoutSec 15 -ErrorAction Stop | Out-Null
        Write-OK "API connection and authentication successful."
    } catch {
        $sc = $_.Exception.Response.StatusCode.Value__
        if ($sc -eq 401)  { Write-Fail "Invalid API Key (401)." }
        elseif ($sc)      { Write-Warn "API returned status: $sc" }
        else              { Write-Fail "Cannot connect to $apiBaseUrl" }
    }
    $ErrorActionPreference = $eap
}

# ============================================================
# clean: Clean Docker build cache
# ============================================================
function Invoke-Clean {
    Write-Info "Cleaning Docker build cache..."
    docker system prune -f
    Write-OK "Cleanup complete."
}

# ============================================================
# help
# ============================================================
function Show-Help {
    $helpText = @(
        "",
        "Usage: .\scripts\manage.ps1 <command> [arg] [-Llm]",
        "",
        "Commands:",
        "  init              Create docker\.env config file",
        "  ssl [IP/hostname] Generate self-signed SSL certificate",
        "  pull              Pull platform base images (requires internet)",
        "  build             Build workspace Docker image (embedded toolchain)",
        "  save              Export all images as tar (for offline transfer)",
        "  load              Load images from images\*.tar (offline deploy)",
        "  up                Start platform (auto SSL, first-time Coder init)",
        "  down              Stop platform",
        "  status            Show container status",
        "  logs [service]    Show logs (gateway / coder / postgres / llm-gateway)",
        "  shell <service>   Enter container shell",
        "  setup-coder       Manually trigger Coder init (create admin + push template)",
        "  test-api          Test LLM API connectivity",
        "  clean             Clean Docker build cache",
        "",
        "Options:",
        "  -Llm              Include LiteLLM AI gateway (requires configs\litellm_config.yaml)",
        "",
        "Examples:",
        "  .\scripts\manage.ps1 init",
        "  .\scripts\manage.ps1 ssl 192.168.1.100",
        "  .\scripts\manage.ps1 build",
        "  .\scripts\manage.ps1 up",
        "  .\scripts\manage.ps1 up -Llm",
        "  .\scripts\manage.ps1 logs coder",
        "  .\scripts\manage.ps1 shell coder",
        "  .\scripts\manage.ps1 down",
        "",
        "Access URLs (after startup):",
        "  Admin Dashboard: https://<IP>:8443/",
        "  User IDE:        https://<IP>:8443/@<username>/<workspace>.main/apps/code-server",
        "  LiteLLM:         https://<IP>:8443/llm/  (with -Llm flag)",
        ""
    )
    Write-Host ($helpText -join "`n")
}

# ============================================================
# Main entry point
# ============================================================
Write-Host "=== Coder Production Platform Management (Windows) ===" -ForegroundColor Blue
Write-Host ""

switch ($Command.ToLower()) {
    "init"        { Initialize-Dirs; Invoke-Init; break }
    "ssl"         { Initialize-Dirs; Invoke-GenSSL -ServerHost $Arg1; break }
    "pull"        { Invoke-Pull; break }
    "build"       { Invoke-Build; break }
    "save"        { Invoke-Save; break }
    "load"        { Invoke-Load; break }
    "up"          { Invoke-Up; break }
    "start"       { Invoke-Up; break }
    "down"        { Invoke-Down; break }
    "stop"        { Invoke-Down; break }
    "status"      { Invoke-Status; break }
    "ps"          { Invoke-Status; break }
    "logs"        { Invoke-Logs; break }
    "shell"       { Invoke-Shell; break }
    "setup-coder" { Invoke-SetupCoder; break }
    "test-api"    { Invoke-TestApi; break }
    "clean"       { Invoke-Clean; break }
    default       { Show-Help }
}
